### ISSUE TITLE
Some thoughts on your project

### ISSUE THREAD

**Issue by abb1991** [dakar303/TeaCozy#1]
Your project looks great! You should feel proud of the work you did. Aesthetically, I have no suggestions for how to improve, so I'll leave a few thoughts about your code organization/styling. 

For your styling, I think you should try and add more classes/ids. When you style generic HTML elements, like p or a, it can come back to cause unexpected styles when you add more elements later in your project. 

I really like how you've organized your HTML. The indentations are great and your use of divs to encapsulate different sections is also a great addition. My one suggestion, which is a small one, is to consider leaving a whitespace between different sections of your site (e.g. between containing divs) it makes your code a bit easier to read.

Overall, really excellent job!

**Comment by dakar303** [comment]
Thank you.
